openapi: 3.0.1
info:
  description: "Use next-generation AI to extract data, fields, insights and text\
    \ from documents. Instantly."
  termsOfService: https://portal.cloudmersive.com/terms-of-service
  title: Document AI API
  version: v1
servers:
- url: /
security:
- Apikey: []
paths:
  /document-ai/document/analyze/enforce-policy:
    post:
      description: "Enforce Policies to a Document to allow or block it using Advanced\
        \ AI.  Input document formats supported include DOCX, PDF, PNG and JPG.  Consumes\
        \ 100 API calls per page."
      operationId: ApplyRules
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentPolicyRequest"
          text/json:
            schema:
              $ref: "#/components/schemas/DocumentPolicyRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/DocumentPolicyRequest"
        description: "Input request, including document and policy rules"
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/DocumentPolicyResult"
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentPolicyResult"
            text/json:
              schema:
                $ref: "#/components/schemas/DocumentPolicyResult"
          description: OK
      summary: Enforce Policies to a Document to allow or block it using Advanced
        AI
      tags:
      - Analyze
      x-codegen-request-body-name: body
  /document-ai/document/extract/text:
    post:
      description: "Extract raw text from a document using AI.  Input document formats\
        \ supported include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.  Supports\
        \ a wide range of languages.  Consumes 100 API calls per page."
      operationId: ExtractText
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractTextResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractTextResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractTextResponse"
          description: OK
      summary: Extract Text from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/fields:
    post:
      description: "Extract Field Values (e.g. Invoice Number, Invoice Date, Business\
        \ Card Phone Number, etc.) from a document using AI.  Input document formats\
        \ supported include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.  Consumes\
        \ 100 API calls per page."
      operationId: ExtractFields
      parameters:
      - description: "Desired fields to extract, comma separated"
        in: header
        name: FieldNames
        schema:
          type: string
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractFieldsResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsResponse"
          description: OK
      summary: Extract Field Values from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/fields/advanced:
    post:
      description: "Extract Field Values (e.g. Invoice Number, Invoice Date, Business\
        \ Card Phone Number, etc.) from a document using Advanced AI.  Input document\
        \ formats supported include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and\
        \ WEBP.  Consumes 100 API calls per page."
      operationId: ExtractFieldsAdvanced
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
          text/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
        description: "Input request, including document file as byte array, and information\
          \ on which fields to extract"
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAdvancedResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAdvancedResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAdvancedResponse"
          description: OK
      summary: Extract Field Values from a Document using Advanced AI
      tags:
      - Extract
      x-codegen-request-body-name: body
  /document-ai/document/extract/tables:
    post:
      description: "Extract Tables, comprised of rows and columns of data, from a\
        \ document using AI.  Input document formats supported include DOCX, PDF,\
        \ XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.  Consumeds 100 API calls per page."
      operationId: ExtractTables
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractTablesResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractTablesResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractTablesResponse"
          description: OK
      summary: Extract Tables of Data from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/barcodes:
    post:
      description: "Extract all barcodes from a document using AI.  Input document\
        \ formats supported include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG, HEIC\
        \ and WEBP.  Consumes 100 API calls per page."
      operationId: ExtractBarcodes
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractBarcodesAiResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractBarcodesAiResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractBarcodesAiResponse"
          description: OK
      summary: Extract Barcodes of from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/all:
    post:
      description: "Extract all Fields and Tables, comprised of rows and columns of\
        \ data, from a document using AI.  Input document formats supported include\
        \ DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.  Consumes 100 API calls\
        \ per page."
      operationId: ExtractAllFieldsAndTables
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      - description: "Optional: Set the level of image pre-processing to enhance accuracy.\
          \  Possible values are 'Auto' (default), 'Paged', and 'Compatability'. \
          \ Use 'Paged' to treat each page as a separate document for extraction (requires\
          \ Advanced recognitionMode).  Default is Auto."
        in: header
        name: preprocessing
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAndTablesResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAndTablesResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractFieldsAndTablesResponse"
          description: OK
      summary: Extract All Fields and Tables of Data from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/classify:
    post:
      description: "Extract Classification or Category (e.g. Invoice, Receipt, Tax\
        \ Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input\
        \ document formats supported include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG,\
        \ PNG and WEBP.  Consumes 100 API calls per page."
      operationId: ExtractClassification
      parameters:
      - description: Desired classification to extract
        in: header
        name: Categories
        schema:
          type: string
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/DocumentClassificationResult"
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentClassificationResult"
            text/json:
              schema:
                $ref: "#/components/schemas/DocumentClassificationResult"
          description: OK
      summary: Extract Classification or Category from a Document using AI
      tags:
      - Extract
  /document-ai/document/extract/classify/advanced:
    post:
      description: "Extract Classification or Category (e.g. Invoice, Receipt, Tax\
        \ Form, or Form 1040, Form 1040 EZ, etc.) from a document using Advanced AI.\
        \  Input document formats supported include DOCX, PDF, XLSX, PPTX, EML, MSG,\
        \ JPG, PNG and WEBP.  Consumes 100 API calls per page."
      operationId: ExtractClassificationAdvanced
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractClassificationRequest"
          text/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractClassificationRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractClassificationRequest"
        description: Input request to perform the classification on
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/DocumentAdvancedClassificationResult"
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentAdvancedClassificationResult"
            text/json:
              schema:
                $ref: "#/components/schemas/DocumentAdvancedClassificationResult"
          description: OK
      summary: Extract Classification or Category from a Document using Advanced AI
      tags:
      - Extract
      x-codegen-request-body-name: body
  /document-ai/document/extract/summary:
    post:
      description: "Creates a 1 paragraph summary of the input document using Artificial\
        \ Intelligence.  Input document formats supported include DOCX, PDF, XLSX,\
        \ PPTX, EML, MSG, JPG, PNG and WEBP.  Consumes 100 API calls per page."
      operationId: ExtractSummary
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/SummarizeDocumentResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/SummarizeDocumentResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/SummarizeDocumentResponse"
          description: OK
      summary: Extract Summary from a Document using AI
      tags:
      - Extract
  /document-ai/document/batch-job/extract/text:
    post:
      description: "Creates an async batch job for processing a large document as\
        \ an AI batch job.  Input document formats supported include DOCX, PDF, PNG\
        \ and JPG.  Supports a wide range of languages.  Requires Managed Instance\
        \ or Private Cloud deployment."
      operationId: ExtractTextFromDocumentBatchJob
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
          description: OK
      summary: Extract Text from a Document using AI as a Batch Job
      tags:
      - RunBatchJob
  /document-ai/document/batch-job/extract/fields/advanced:
    post:
      description: "Creates an async batch job for processing a large document as\
        \ an AI batch job.  Extract Field Values (e.g. Invoice Number, Invoice Date,\
        \ Business Card Phone Number, etc.) from a document using Advanced AI.  Input\
        \ document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed\
        \ Instance or Private Cloud deployment."
      operationId: ExtractFieldsFromDocumentAdvancedBatchJob
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
          text/json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/AdvancedExtractFieldsRequest"
        required: false
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
          description: OK
      summary: Extract Field Values from a Document using Advanced AI as a Batch Job
      tags:
      - RunBatchJob
      x-codegen-request-body-name: body
  /document-ai/document/batch-job/extract/all:
    post:
      description: "Creates an async batch job for processing a large document as\
        \ an AI batch job.  Extract all Fields and Tables, comprised of rows and columns\
        \ of data, from a document using AI.  Input document formats supported include\
        \ DOCX, PDF, PNG and JPG.  Requires Managed Instance or Private Cloud deployment."
      operationId: ExtractAllFieldsAndTablesFromDocumentBatchJob
      parameters:
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
          description: OK
      summary: Extract All Fields and Tables of Data from a Document using AI as a
        Batch Job
      tags:
      - RunBatchJob
  /document-ai/document/batch-job/extract/classify:
    post:
      description: "Creates an async batch job for processing a large document as\
        \ an AI batch job.  Extract Classification or Category (e.g. Invoice, Receipt,\
        \ Tax Form, or Form 1040, Form 1040 EZ, etc.) from a document using AI.  Input\
        \ document formats supported include DOCX, PDF, PNG and JPG.  Requires Managed\
        \ Instance or Private Cloud deployment."
      operationId: ExtractClassificationFromDocumentBatchJob
      parameters:
      - description: Desired classification to extract
        in: header
        name: Categories
        schema:
          type: string
      - description: "Optional; Recognition mode - Advanced (default) provides the\
          \ highest accuracy but slower speed, while Normal provides faster response\
          \ but lower accuracy for low quality images"
        in: header
        name: recognitionMode
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractText_request"
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentBatchJobResult"
          description: OK
      summary: Extract Classification or Category from a Document using AI as a Batch
        Job
      tags:
      - RunBatchJob
  /document-ai/document/batch-job/batch-job/status:
    get:
      description: Returns the result of the Async Job - possible states can be STARTED
        or COMPLETED.  This API is only available for Cloudmersive Managed Instance
        and Private Cloud deployments.
      operationId: GetAsyncJobStatus
      parameters:
      - in: query
        name: AsyncJobID
        schema:
          type: string
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ExtractDocumentJobStatusResult"
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentJobStatusResult"
            text/json:
              schema:
                $ref: "#/components/schemas/ExtractDocumentJobStatusResult"
          description: OK
      summary: Get the status and result of an Extract Document Batch Job
      tags:
      - RunBatchJob
components:
  schemas:
    AdvancedExtractClassificationRequest:
      additionalProperties: false
      description: Request to perform an AI document classification on a document
      example:
        MaximumPagesProcessed: 0
        Preprocessing: Preprocessing
        Categories:
        - CategoryName: CategoryName
          CategoryDescription: CategoryDescription
        - CategoryName: CategoryName
          CategoryDescription: CategoryDescription
        ResultCrossCheck: ResultCrossCheck
        RotateImageDegrees: 6.027456183070403
        InputFile: InputFile
      properties:
        InputFile:
          description: Input document file to perform the operation on as a byte array
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        Categories:
          description: Possible categories for the document
          items:
            $ref: "#/components/schemas/DocumentCategories"
          type: array
        Preprocessing:
          description: "Optional: Set the level of image pre-processing to enhance\
            \ accuracy.  Possible values are 'Auto', 'SmoothEdges', 'SmoothEdgesPlus',\
            \ 'Compatability' and 'None'.  Default is Auto.  Set to SmoothEdges to\
            \ smooth harsh edges in the input image to enhance recognition accuracy.\
            \  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree.  Set\
            \ to Compatability for maximum PDF feature compatability."
          type: string
        ResultCrossCheck:
          description: "Optional: Set the level of output accuracy cross-checking\
            \ to perform on the input.  Possible values are 'None', 'Advanced', 'Ultra'\
            \ and 'Hyper'.  Default is None.  Ultra and Hyper will produce the highest\
            \ accuracy but at the cost of longer processing times."
          type: string
        MaximumPagesProcessed:
          description: "Optional: Limit the number of pages processed"
          format: int32
          type: integer
        RotateImageDegrees:
          description: "Optional: Rotate the input image before recognition by the\
            \ specified number of degrees; valid values range from -360 to +360."
          format: double
          type: number
      type: object
    AdvancedExtractFieldsRequest:
      additionalProperties: false
      description: Request to perform an AI field extraction on a document
      example:
        MaximumPagesProcessed: 0
        Preprocessing: Preprocessing
        ResultCrossCheck: ResultCrossCheck
        RotateImageDegrees: 6.027456183070403
        FieldsToExtract:
        - FieldOptional: true
          FieldExample: FieldExample
          FieldName: FieldName
          FieldDescription: FieldDescription
        - FieldOptional: true
          FieldExample: FieldExample
          FieldName: FieldName
          FieldDescription: FieldDescription
        InputFile: InputFile
      properties:
        InputFile:
          description: Input document file to perform the operation on as a byte array
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        FieldsToExtract:
          description: Fields to extract from the document
          items:
            $ref: "#/components/schemas/FieldToExtract"
          type: array
        MaximumPagesProcessed:
          description: "Optional: Limit the number of pages processed"
          format: int32
          type: integer
        Preprocessing:
          description: "Optional: Set the level of image pre-processing to enhance\
            \ accuracy.  Possible values are 'Auto', 'SmoothEdges', 'SmoothEdgesPlus',\
            \ 'ContrastEdges', 'ContrastEdgesPlus', 'Invert', 'Binarize', 'Compatability'\
            \ and 'None'.  Default is Auto.  Set to SmoothEdges to smooth harsh edges\
            \ in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus\
            \ to smooth harsh edges to a higher degree.  Set to ContrastEdges and\
            \ ContrastEdgesPlus to enhance contrast and readability for low quality\
            \ black and white or grayscale images.  Set to Invert to invert the input\
            \ image.  Set to Binarize to binarize the input image.  Set to Compatability\
            \ for maximum PDF feature compatability."
          type: string
        ResultCrossCheck:
          description: "Optional: Set the level of output accuracy cross-checking\
            \ to perform on the input.  Possible values are 'None', 'Advanced' and\
            \ 'Ultra'.  Default is None.  Ultra will produce the highest accuracy\
            \ but at the cost of longer processing times."
          type: string
        RotateImageDegrees:
          description: "Optional: Rotate the input image before recognition by the\
            \ specified number of degrees; valid values range from -360 to +360."
          format: double
          type: number
      type: object
    DocumentAdvancedClassificationResult:
      additionalProperties: false
      description: Result of classifying a document using AI
      example:
        DocumentCategoryResult: DocumentCategoryResult
        ConfidenceScore: 0.8008281904610115
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        DocumentCategoryResult:
          description: Category applied to the document; if a category could not be
            identified then "other" will be used.  Spaces are replaced with underscores.
          type: string
        ConfidenceScore:
          description: "Confidence score between 0.0 and 1.0, where values > 0.8 indicate\
            \ high confidence"
          format: double
          type: number
      type: object
    DocumentCategories:
      additionalProperties: false
      description: Document category option
      example:
        CategoryName: CategoryName
        CategoryDescription: CategoryDescription
      properties:
        CategoryName:
          description: Name of the classification
          type: string
        CategoryDescription:
          description: "Optional but recommended: Description of the classification\
            \ in natural langugage"
          type: string
      type: object
    DocumentClassificationResult:
      additionalProperties: false
      description: Result of classifying a document using AI
      example:
        DocumentCategoryResult: DocumentCategoryResult
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        DocumentCategoryResult:
          description: Category applied to the document; if a category could not be
            identified then "other" will be used.  Spaces are replaced with underscores.
          type: string
      type: object
    DocumentPolicyRequest:
      additionalProperties: false
      description: Request to analyze a document
      example:
        Rules:
        - RuleDescription: RuleDescription
          RuleId: RuleId
          RuleType: RuleType
        - RuleDescription: RuleDescription
          RuleId: RuleId
          RuleType: RuleType
        InputFile: InputFile
      properties:
        InputFile:
          description: Input file as a byte array
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
        Rules:
          description: Rules to apply to the document
          items:
            $ref: "#/components/schemas/PolicyRule"
          type: array
      type: object
    DocumentPolicyResult:
      additionalProperties: false
      description: Result of performing a document policy enforcement operation
      example:
        RiskScore: 0.8008281904610115
        RuleViolations:
        - RuleId: RuleId
          RuleViolationRiskScore: 6.027456183070403
          RuleViolationRationale: RuleViolationRationale
        - RuleId: RuleId
          RuleViolationRiskScore: 6.027456183070403
          RuleViolationRationale: RuleViolationRationale
        CleanResult: true
      properties:
        CleanResult:
          description: "True if the document complies with all of the policies, and\
            \ false if it does not"
          type: boolean
        RiskScore:
          description: Risk score between 0.0 and 1.0 where values above 0.5 are increasing
            levels of risk
          format: double
          type: number
        RuleViolations:
          description: Policy violations
          items:
            $ref: "#/components/schemas/PolicyRuleViolation"
          type: array
      type: object
    ExtractBarcodesAiResponse:
      additionalProperties: false
      description: Result of extracting barcodes from a document
      example:
        BarcodeResults:
        - BarcodeValue: BarcodeValue
          BarcodeType: BarcodeType
        - BarcodeValue: BarcodeValue
          BarcodeType: BarcodeType
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        BarcodeResults:
          description: Table value results from the extraction operation
          items:
            $ref: "#/components/schemas/ExtractedBarcodeItem"
          type: array
      type: object
    ExtractDocumentBatchJobResult:
      additionalProperties: false
      description: Result of performing a split document batch job
      example:
        AsyncJobID: AsyncJobID
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        AsyncJobID:
          description: "When creating a job, an Async Job ID is returned.  Use the\
            \ GetAsyncJobStatus API to check on the status of this job using the AsyncJobID\
            \ and get the result when it finishes"
          type: string
      type: object
    ExtractDocumentJobStatusResult:
      additionalProperties: false
      description: Result of performing a batch job operation
      example:
        ExtractFieldsAndTablesResult:
          TableResults:
          - Title: Title
            Rows:
            - Cells:
              - CellValue: CellValue
                CellHeader: CellHeader
              - CellValue: CellValue
                CellHeader: CellHeader
            - Cells:
              - CellValue: CellValue
                CellHeader: CellHeader
              - CellValue: CellValue
                CellHeader: CellHeader
          - Title: Title
            Rows:
            - Cells:
              - CellValue: CellValue
                CellHeader: CellHeader
              - CellValue: CellValue
                CellHeader: CellHeader
            - Cells:
              - CellValue: CellValue
                CellHeader: CellHeader
              - CellValue: CellValue
                CellHeader: CellHeader
          Successful: true
          FieldResults:
          - FieldName: FieldName
            FieldStringValue: FieldStringValue
            AdditionalFieldStringValues:
            - AdditionalFieldStringValues
            - AdditionalFieldStringValues
          - FieldName: FieldName
            FieldStringValue: FieldStringValue
            AdditionalFieldStringValues:
            - AdditionalFieldStringValues
            - AdditionalFieldStringValues
        ExtractClassificationResult:
          DocumentCategoryResult: DocumentCategoryResult
          Successful: true
        ExtractTextResult:
          PageResults:
          - TextResult: TextResult
            PageNumber: 0
          - TextResult: TextResult
            PageNumber: 0
          Successful: true
        ExtractFieldsResult:
          Results:
          - FieldName: FieldName
            FieldStringValue: FieldStringValue
            AdditionalFieldStringValues:
            - AdditionalFieldStringValues
            - AdditionalFieldStringValues
          - FieldName: FieldName
            FieldStringValue: FieldStringValue
            AdditionalFieldStringValues:
            - AdditionalFieldStringValues
            - AdditionalFieldStringValues
          Successful: true
        AsyncJobID: AsyncJobID
        ErrorMessage: ErrorMessage
        Successful: true
        AsyncJobStatus: AsyncJobStatus
      properties:
        Successful:
          description: "True if the operation to check the status of the job was successful,\
            \ false otherwise"
          type: boolean
        AsyncJobStatus:
          description: "Returns the job status of the Async Job, if applicable.  Possible\
            \ states are STARTED and COMPLETED"
          type: string
        AsyncJobID:
          description: Job ID
          type: string
        ExtractTextResult:
          $ref: "#/components/schemas/ExtractTextResponse"
        ExtractFieldsAndTablesResult:
          $ref: "#/components/schemas/ExtractFieldsAndTablesResponse"
        ExtractFieldsResult:
          $ref: "#/components/schemas/ExtractFieldsResponse"
        ExtractClassificationResult:
          $ref: "#/components/schemas/DocumentClassificationResult"
        ErrorMessage:
          description: Error message (if any)
          type: string
      type: object
    ExtractFieldsAdvancedResponse:
      additionalProperties: false
      description: Result of extracting fields from a document
      example:
        Results:
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
        ConfidenceScore: 0.8008281904610115
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        Results:
          description: Field value results from the extraction operation
          items:
            $ref: "#/components/schemas/FieldAdvancedValue"
          type: array
        ConfidenceScore:
          description: "Confidence score between 0.0 and 1.0, where values > 0.8 indicate\
            \ high confidence"
          format: double
          type: number
      type: object
    ExtractFieldsAndTablesResponse:
      additionalProperties: false
      description: Result of extracting fields from a document
      example:
        TableResults:
        - Title: Title
          Rows:
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
        - Title: Title
          Rows:
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
        Successful: true
        FieldResults:
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
          AdditionalFieldStringValues:
          - AdditionalFieldStringValues
          - AdditionalFieldStringValues
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
          AdditionalFieldStringValues:
          - AdditionalFieldStringValues
          - AdditionalFieldStringValues
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        FieldResults:
          description: Field value results from the extraction operation
          items:
            $ref: "#/components/schemas/FieldValue"
          type: array
        TableResults:
          description: Table value results from the extraction operation
          items:
            $ref: "#/components/schemas/TableResult"
          type: array
      type: object
    ExtractFieldsResponse:
      additionalProperties: false
      description: Result of extracting fields from a document
      example:
        Results:
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
          AdditionalFieldStringValues:
          - AdditionalFieldStringValues
          - AdditionalFieldStringValues
        - FieldName: FieldName
          FieldStringValue: FieldStringValue
          AdditionalFieldStringValues:
          - AdditionalFieldStringValues
          - AdditionalFieldStringValues
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        Results:
          description: Field value results from the extraction operation
          items:
            $ref: "#/components/schemas/FieldValue"
          type: array
      type: object
    ExtractTablesResponse:
      additionalProperties: false
      description: Result of extracting tables from a document
      example:
        TableResults:
        - Title: Title
          Rows:
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
        - Title: Title
          Rows:
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
          - Cells:
            - CellValue: CellValue
              CellHeader: CellHeader
            - CellValue: CellValue
              CellHeader: CellHeader
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        TableResults:
          description: Table value results from the extraction operation
          items:
            $ref: "#/components/schemas/TableResult"
          type: array
      type: object
    ExtractTextResponse:
      additionalProperties: false
      description: Result of extracting text from a document
      example:
        PageResults:
        - TextResult: TextResult
          PageNumber: 0
        - TextResult: TextResult
          PageNumber: 0
        Successful: true
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        PageResults:
          description: Page results from the extraction operation
          items:
            $ref: "#/components/schemas/ExtractedTextPage"
          type: array
      type: object
    ExtractedBarcodeItem:
      additionalProperties: false
      description: Extracted barcode result
      example:
        BarcodeValue: BarcodeValue
        BarcodeType: BarcodeType
      properties:
        BarcodeType:
          description: "Type of the barcode identified, possible values are: AZTEC,\
            \ CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF,\
            \ MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D,\
            \ UPC_EAN_EXTENSION, MSI, PLESSEY, IMB, UNKNOWN"
          type: string
        BarcodeValue:
          description: Value of the barcode as a string
          type: string
      type: object
    ExtractedTextPage:
      additionalProperties: false
      description: Extracted page from an input document
      example:
        TextResult: TextResult
        PageNumber: 0
      properties:
        PageNumber:
          description: "Page number index, 1-based"
          format: int32
          type: integer
        TextResult:
          description: Text content of the page
          type: string
      type: object
    FieldAdvancedValue:
      additionalProperties: false
      description: Field value result of extracting fields from a document
      example:
        FieldName: FieldName
        FieldStringValue: FieldStringValue
      properties:
        FieldName:
          description: Name of the field (note that spaces will be replaced with underscore)
          type: string
        FieldStringValue:
          description: String value of the field that was extractged from the document
          type: string
      type: object
    FieldToExtract:
      additionalProperties: false
      description: Field to extract from a document using AI
      example:
        FieldOptional: true
        FieldExample: FieldExample
        FieldName: FieldName
        FieldDescription: FieldDescription
      properties:
        FieldName:
          description: Name of the field to extract
          type: string
        FieldOptional:
          description: "Optional: True if the field is optional, false if required\
            \ (default)"
          type: boolean
        FieldDescription:
          description: "Optional but recommended: Description of the field - use this\
            \ to describe what the field is, how it is formatted, what is unique about\
            \ it, etc."
          type: string
        FieldExample:
          description: "Optional: Example label or value of the field"
          type: string
      type: object
    FieldValue:
      additionalProperties: false
      description: Field value result of extracting fields from a document
      example:
        FieldName: FieldName
        FieldStringValue: FieldStringValue
        AdditionalFieldStringValues:
        - AdditionalFieldStringValues
        - AdditionalFieldStringValues
      properties:
        FieldName:
          description: Name of the field (note that spaces will be replaced with underscore)
          type: string
        FieldStringValue:
          description: Primary or first string value of the field that was extractged
            from the document
          type: string
        AdditionalFieldStringValues:
          description: "Additional values for this field when the same field is present\
            \ with multiple values, for example, if two instances of the same form\
            \ occur in the same document"
          items:
            type: string
          type: array
      type: object
    PolicyRule:
      additionalProperties: false
      example:
        RuleDescription: RuleDescription
        RuleId: RuleId
        RuleType: RuleType
      properties:
        RuleId:
          description: ""
          type: string
        RuleType:
          description: Possible values are ALLOW and DENY
          type: string
        RuleDescription:
          description: "Description of the rule in natural language, e.g. Do not allow\
            \ documents that contain offensive language"
          type: string
      type: object
    PolicyRuleViolation:
      additionalProperties: false
      description: Instances of a policy rule violation
      example:
        RuleId: RuleId
        RuleViolationRiskScore: 6.027456183070403
        RuleViolationRationale: RuleViolationRationale
      properties:
        RuleId:
          description: "ID of the rule; if no ID was supplied, the ID is the 1-based\
            \ index of the rule"
          type: string
        RuleViolationRiskScore:
          description: Risk score between 0.0 and 1.0 where values above 0.5 are increasing
            levels of risk
          format: double
          type: number
        RuleViolationRationale:
          description: AI natural language rationale for why this policy was violated
          type: string
      type: object
    SummarizeDocumentResponse:
      additionalProperties: false
      description: Result of summarizing a document
      example:
        Successful: true
        DocumentSummaryText: DocumentSummaryText
      properties:
        Successful:
          description: "True if successful, false otherwise"
          type: boolean
        DocumentSummaryText:
          description: Summary of the document
          type: string
      type: object
    TableResult:
      additionalProperties: false
      description: Table extracted from a document
      example:
        Title: Title
        Rows:
        - Cells:
          - CellValue: CellValue
            CellHeader: CellHeader
          - CellValue: CellValue
            CellHeader: CellHeader
        - Cells:
          - CellValue: CellValue
            CellHeader: CellHeader
          - CellValue: CellValue
            CellHeader: CellHeader
      properties:
        Title:
          description: Title of the table (optional)
          type: string
        Rows:
          description: Rows of the table
          items:
            $ref: "#/components/schemas/TableResultRow"
          type: array
      type: object
    TableResultCell:
      additionalProperties: false
      description: Cell of a row of a table extracted from a document
      example:
        CellValue: CellValue
        CellHeader: CellHeader
      properties:
        CellHeader:
          description: Cell column header
          type: string
        CellValue:
          description: Cell value as a string
          type: string
      type: object
    TableResultRow:
      additionalProperties: false
      description: Row of a table extracted from a document
      example:
        Cells:
        - CellValue: CellValue
          CellHeader: CellHeader
        - CellValue: CellValue
          CellHeader: CellHeader
      properties:
        Cells:
          description: Cells in the row
          items:
            $ref: "#/components/schemas/TableResultCell"
          type: array
      type: object
    ExtractText_request:
      properties:
        InputFile:
          description: "Input document, or photos of a document, to extract data from"
          format: binary
          type: string
      type: object
  securitySchemes:
    Apikey:
      description: API Key Authentication
      in: header
      name: Apikey
      type: apiKey
x-original-swagger-version: "2.0"

